[toolchain]
channel = "nightly-2024-05-01"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = b60a1555155111e962018007a6d0ef85207db463

# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
